### ISSUE TITLE
[BUG] Cvar mp_maxrounds set less than 2. Plugin can't work correctly with these settings.

### ISSUE THREAD

**Issue by crashzk** [ssypchenko/GG1MapChooser#2]
I'm getting this error log on the servers:
```
2024-06-21 11:59:06.068 -03:00 [EROR] plugin:GG1_MapChooser VoteDependsOnRoundWins set true, but cvar mp_maxrounds set less than 2. Plugin can't work correctly with these settings.
```

However, in both **server.cfg** and **gamemode_competitive_server.cfg** the cvar `mp_maxrounds` is set to `24`.

![image](https://github.com/ssypchenko/GG1MapChooser/assets/32937653/250afd91-848a-4f53-8f8c-8abcda3908fa)

Full error log:
```
2024-06-21 11:59:06.068 -03:00 [EROR] plugin:GG1_MapChooser VoteDependsOnRoundWins set true, but cvar mp_maxrounds set less than 2. Plugin can't work correctly with these settings.
2024-06-21 11:59:06.082 -03:00 [INFO] plugin:GG1_MapChooser GGMC API registered
2024-06-21 11:59:09.536 -03:00 [INFO] plugin:GG1_MapChooser de_mirage loaded
2024-06-21 11:59:09.537 -03:00 [INFO] plugin:GG1_MapChooser ResetData from On Map Start
2024-06-21 11:59:09.537 -03:00 [INFO] plugin:GG1_MapChooser On Initialise Map set: MaxRoundsValue 24, CanClinch true
2024-06-21 11:59:12.707 -03:00 [INFO] plugin:GG1_MapChooser ResetData from On last client disconnect
2024-06-21 11:59:12.707 -03:00 [INFO] plugin:GG1_MapChooser On Initialise Map set: MaxRoundsValue 24, CanClinch true
2024-06-21 11:59:12.892 -03:00 [INFO] plugin:GG1_MapChooser de_mirage loaded
2024-06-21 11:59:12.892 -03:00 [INFO] plugin:GG1_MapChooser ResetData from On Map Start
2024-06-21 11:59:12.892 -03:00 [INFO] plugin:GG1_MapChooser On Initialise Map set: MaxRoundsValue 24, CanClinch true
2024-06-21 11:59:16.463 -03:00 [INFO] plugin:GG1_MapChooser UnlimitedRounds false, RemainingRounds 24, RemainingWins 13
2024-06-21 11:59:16.463 -03:00 [INFO] plugin:GG1_MapChooser Round start, canVote True, Warmup False 
2024-06-21 11:59:16.479 -03:00 [INFO] plugin:GG1_MapChooser UnlimitedRounds false, RemainingRounds 24, RemainingWins 13
2024-06-21 11:59:16.479 -03:00 [INFO] plugin:GG1_MapChooser Round start, canVote True, Warmup False 
2024-06-21 12:04:39.962 -03:00 [INFO] plugin:GG1_MapChooser Round start, canVote True, Warmup True 
2024-06-21 12:04:45.207 -03:00 [INFO] plugin:GG1_MapChooser T Wins 0, CTWins 0
2024-06-21 12:04:45.249 -03:00 [INFO] plugin:GG1_MapChooser Round start, canVote True, Warmup True 
2024-06-21 12:04:53.047 -03:00 [EROR] plugin:GG1_MapChooser VoteDependsOnRoundWins set true, but cvar mp_maxrounds set less than 2. Plugin can't work correctly with these settings.
2024-06-21 12:04:53.062 -03:00 [INFO] plugin:GG1_MapChooser GGMC API registered
2024-06-21 12:04:56.531 -03:00 [INFO] plugin:GG1_MapChooser de_mirage loaded
2024-06-21 12:04:56.532 -03:00 [INFO] plugin:GG1_MapChooser ResetData from On Map Start
2024-06-21 12:04:56.533 -03:00 [INFO] plugin:GG1_MapChooser On Initialise Map set: MaxRoundsValue 24, CanClinch true
2024-06-21 12:05:00.082 -03:00 [INFO] plugin:GG1_MapChooser ResetData from On last client disconnect
2024-06-21 12:05:00.082 -03:00 [INFO] plugin:GG1_MapChooser On Initialise Map set: MaxRoundsValue 24, CanClinch true
2024-06-21 12:05:00.263 -03:00 [INFO] plugin:GG1_MapChooser de_mirage loaded
2024-06-21 12:05:00.263 -03:00 [INFO] plugin:GG1_MapChooser ResetData from On Map Start
2024-06-21 12:05:00.264 -03:00 [INFO] plugin:GG1_MapChooser On Initialise Map set: MaxRoundsValue 24, CanClinch true
2024-06-21 12:05:04.028 -03:00 [INFO] plugin:GG1_MapChooser UnlimitedRounds false, RemainingRounds 24, RemainingWins 13
2024-06-21 12:05:04.028 -03:00 [INFO] plugin:GG1_MapChooser Round start, canVote True, Warmup False 
2024-06-21 12:05:04.043 -03:00 [INFO] plugin:GG1_MapChooser UnlimitedRounds false, RemainingRounds 24, RemainingWins 13
2024-06-21 12:05:04.043 -03:00 [INFO] plugin:GG1_MapChooser Round start, canVote True, Warmup False 
```

**Comment by ssypchenko** [comment]
Thank you. It is unusual behaviour for me of cvar queries. I moved the check to another place so I think it should work now without this error. Can you please check? However, it was just an informational message and the plugin should work correctly.

**Comment by ssypchenko** [comment]
it was improved in the latest releases.

**Comment by crashzk** [comment]
@ssypchenko problem still occurs.

```
2024-08-24 08:09:08.828 -03:00 [INFO] plugin:GG1_MapChooser v1.4.2
2024-08-24 08:09:08.829 -03:00 [INFO] plugin:GG1_MapChooser GGMC API registered
2024-08-24 08:09:11.838 -03:00 [INFO] plugin:GG1_MapChooser On Initialise Map set: CanClinch true
2024-08-24 08:09:11.852 -03:00 [EROR] plugin:GG1_MapChooser VoteDependsOnRoundWins set true, but cvar mp_maxrounds set less than 2. Plugin can't work correctly with these settings.
2024-08-24 08:09:11.860 -03:00 [INFO] plugin:GG1_MapChooser v1.4.2
2024-08-24 08:09:11.861 -03:00 [INFO] plugin:GG1_MapChooser GGMC API registered
```

To test, I even put the cvar **`mp_maxrounds`** in **`server.cfg`** and still nothing, even though it shows the error.
